<?php
// Sessions validation between pages
// Starting the session
session_start();
// session_id() returns the actual session ID created by the server.
$SID = session_id();
// Display text to the web page
echo 'Sessions Page Two <br />';
// Display user variable
echo 'User variable: '.$_SESSION['user'];
// Display the session ID that was generated by the session_start() command
echo ' <br /> Session_id: '.$SID;
echo ' <br /><br /><br />';
// Create and display a link for the previous page.
echo '<a href="sessions1.php">Sessions Page One</a> ';
echo ' <br/> <br/> <br/>';
// Create and display a link for the next page.
echo '<a href="sessions3.php">Sessions Logout Page</a> ';
?>