CREATE SCHEMA IF NOT EXISTS `CONNECTION`;

DROP TABLE IF EXISTS `CONNECTION`.`CONNECTION_TEST`;

CREATE TABLE `CONNECTION`.`CONNECTION_TEST` (
  `CT_ID` INT NOT NULL AUTO_INCREMENT,
  `CT_NAME` VARCHAR(45) NULL,
  `CT_COLOR` VARCHAR(45) NULL,
  PRIMARY KEY (`CT_ID`) )
ENGINE = InnoDB;

INSERT INTO `CONNECTION`.`CONNECTION_TEST` (`CT_NAME`, `CT_COLOR`) VALUES (NULL, 'Brenden', 'Red');
INSERT INTO `CONNECTION`.`CONNECTION_TEST` (`CT_NAME`, `CT_COLOR`) VALUES (NULL,'Harmony', 'Blue');
INSERT INTO `CONNECTION`.`CONNECTION_TEST` (`CT_NAME`, `CT_COLOR`) VALUES (NULL,'Bobby', 'Yellow');
INSERT INTO `CONNECTION`.`CONNECTION_TEST` (`CT_NAME`, `CT_COLOR`) VALUES (NULL,'Toby', 'Brown');

SELECT * FROM CONNECTION.CONNECTION_TEST;